from PIL import Image, ImageDraw, ImageFont
FP='/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf'
FIRST,LAST=0x20,0x7e; W,H,ADV=6,8,7
f=ImageFont.truetype(FP,9)
data=bytearray()
for code in range(FIRST,LAST+1):
    img=Image.new('L',(16,16),0)
    ImageDraw.Draw(img).text((0,-1),chr(code),fill=255,font=f)
    px=img.load()
    for c in range(W):
        col=0
        for r in range(H):
            if px[c+1,r+1]>110: col|=(1<<r)
        data.append(col)
# emit module
lines=[]
lines.append('# Desc: Nova D1 shared bitmap font — 6x8 bold (legible on the OLED).')
lines.append('# File: /Packages/NovaD1/novafont.py')
lines.append('#')
lines.append('# Column-packed 1-bit glyphs, ASCII 0x20..0x7e. Each glyph = WIDTH bytes;')
lines.append('# byte = one column, bit (1<<row) = a pixel (row 0 = top). Matches the')
lines.append('# MONO_VLSB canvas so device == PC mock. Generated by repo/tools/novad1/genfont.py.')
lines.append('')
lines.append('FIRST = 0x%02x'%FIRST)
lines.append('WIDTH = %d'%W)
lines.append('HEIGHT = %d'%H)
lines.append('ADVANCE = %d'%ADV)
lines.append('')
# chunk DATA bytes nicely
b=bytes(data)
hexs=''.join('\\x%02x'%v for v in b)
# wrap at ~ 24 bytes (96 chars) per line
chunk=24*4
parts=[hexs[i:i+chunk] for i in range(0,len(hexs),chunk)]
lines.append('DATA = (')
for p in parts:
    lines.append("    b'%s'"%p)
lines.append(')')
lines.append('')
open('RPCortex-repo/repo/packages/novad1/novafont.py','w').write('\n'.join(lines))
print('wrote novafont.py', len(b),'bytes data,', (LAST-FIRST+1),'glyphs')
