# Desc: Nova D1 power — battery %, USB-power detect, low-battery flag, CPU clock.
# File: /Packages/NovaD1/novapower.py
#
# Reads ONLY when the relevant pin is configured, so an unwired/floating ADC can
# never produce a lying battery icon or a spurious low-power popup:
#   Apps.NovaD1_PIN_battery -> ADC pin through a divider (Apps.NovaD1_BattDiv, def 2.0)
#   Apps.NovaD1_PIN_vbus    -> a VBUS-sense GPIO (high = on USB).  No pin = unknown.
# A reading outside 2.5..4.6 V is treated as 'no battery' (floating input). Cached
# ~5s so the status bar doesn't hammer the ADC every frame. MicroPython-safe.

_cache = {'t': None, 'd': None}
_EMPTY = {'have': False, 'pct': 0, 'volts': 0.0, 'usb': None, 'low': False}


from novacore import reg as _reg
import novaboard as _board


def _pin(name, d=None):
    """Resolve a pin through the board profile (see novaboard). With no default
    this returns None for an unconfigured pin, which is what the guard below
    relies on — novaboard keeps 'battery' and 'vbus' out of every board profile
    (novaboard.OPT_IN) precisely so they stay unset until the user wires them."""
    return _board.pin(name, d)


_pinnum = _pin       # the call sites below pass a full registry key; both work


def _read_raw():
    d = dict(_EMPTY)
    import machine
    bp = _pinnum('Apps.NovaD1_PIN_battery')
    if bp is not None:
        try:
            adc = machine.ADC(machine.Pin(bp))
            try:
                adc.atten(machine.ADC.ATTN_11DB)
            except Exception:
                pass
            raw = 0
            for _ in range(8):
                raw += adc.read_u16()
            v = (raw / 8) / 65535 * 3.3
            try:
                div = float(_reg('Apps.NovaD1_BattDiv', '2.0'))
            except (TypeError, ValueError):
                div = 2.0
            volts = v * div
            if 2.5 <= volts <= 4.6:               # plausible LiPo range
                d['have'] = True
                d['volts'] = volts
                d['pct'] = int(max(0, min(100, (volts - 3.3) / (4.2 - 3.3) * 100)))
        except Exception:
            pass
    vp = _pinnum('Apps.NovaD1_PIN_vbus')
    if vp is not None:
        try:
            d['usb'] = bool(machine.Pin(vp, machine.Pin.IN).value())
        except Exception:
            d['usb'] = None
    else:
        # No wired VBUS pin: on Pico W-class boards USB power is readable from the
        # wireless module's VBUS-sense line ('WL_GPIO2'), so USB vs battery can be
        # told apart with no extra wiring. Silently stays None on other boards.
        try:
            d['usb'] = bool(machine.Pin('WL_GPIO2', machine.Pin.IN).value())
        except Exception:
            d['usb'] = None
    try:
        low_th = int(_reg('Apps.NovaD1_LowPct', '15'))
    except (TypeError, ValueError):
        low_th = 15
    d['low'] = d['have'] and d['pct'] < low_th and (d['usb'] is not True)
    return d


def read():
    try:
        import utime
        now = utime.ticks_ms()
    except Exception:
        return _read_raw()
    if _cache['d'] is None or _cache['t'] is None or utime.ticks_diff(now, _cache['t']) > 5000:
        try:
            _cache['d'] = _read_raw()
        except Exception:
            _cache['d'] = dict(_EMPTY)
        _cache['t'] = now
    return _cache['d']


# --------------------------------------------------------------------------
# CPU clock
#
# Lives here rather than in a module of its own because clock and power are the
# same knob on an MCU: the only reason to run slower is to draw less. Both the
# Settings row and the Resources screen read through these, so neither has to
# know the platform rules.
# --------------------------------------------------------------------------

def clock_mhz():
    """Current CPU frequency in MHz, or 0 when it can't be read (host tests)."""
    try:
        import machine
        f = machine.freq()
        if isinstance(f, tuple):
            f = f[0]
        return int(f) // 1000000
    except Exception:
        return 0


def clock_steps():
    """The frequencies the Settings row offers, low to high.

    Taken from hwinfo.clock_range_mhz() so the D1 never invents a limit the OS
    doesn't agree with — that range is the one place port rules live, and RP2
    below 80 MHz breaks flash timing. ESP32 only accepts 80/160/240, so the steps
    are filtered to the range rather than generated by arithmetic. Falls back to
    the RP2 range when hwinfo is missing, which is what the host tests see."""
    lo, hi = 80, 220
    try:
        import hwinfo
        lo, hi = hwinfo.clock_range_mhz()
    except Exception:
        pass
    steps = [s for s in (80, 100, 125, 133, 150, 160, 200, 220, 240) if lo <= s <= hi]
    # The port's own maximum is always offerable even if it isn't on the list.
    if hi not in steps:
        steps.append(hi)
    return steps


def set_clock(mhz, persist=True):
    """Change the CPU clock now, and (by default) make it stick across reboots.

    Two separate effects, and both are wanted: machine.freq() takes effect
    immediately so the change is visible, while Hardware.Boot_Clock is what
    Core/post.py reads on the next boot. Setting only the live frequency would
    silently revert on reset; setting only the key would do nothing until reset.

    Returns the frequency actually in effect afterwards. Raises nothing — a
    refused frequency leaves the board where it was, and the caller sees that in
    the returned value."""
    try:
        mhz = int(mhz)
    except Exception:
        return clock_mhz()
    steps = clock_steps()
    if steps and (mhz < steps[0] or mhz > steps[-1]):
        return clock_mhz()
    try:
        import machine
        machine.freq(mhz * 1000000)
    except Exception:
        # A port that refuses the value leaves the clock alone; don't persist a
        # frequency the hardware has already rejected.
        return clock_mhz()
    if persist:
        try:
            from novacore import save_reg as _save
            _save('Hardware.Boot_Clock', '{:.1f}MHz'.format(float(mhz)))
            _save('Settings.OC_On_Boot', 'true')
        except Exception:
            pass
    return clock_mhz()
